### ISSUE TITLE
[todo] document yaml type coercion 

### ISSUE THREAD

**Issue by GeoffWilliams** [GeoffWilliams/puppet-windows_firewall#1]
If supplying data from `yaml` files, you MUST put quotes around `on` and `off`, otherwise yaml will coerce them into booleans which will break the logic of the module (and probably lock you out of the server in the process)

Eg, you must do something like:

```yaml
  private:
      state: 'on'
   public:
      state: 'on'
   domain:
      state: 'on'
```

Document this and or make the type handling looser/tighter
